server:
    error:
        include-message: always
    port: 8081
spring:
    application:
        name: spring-boot-example
    datasource:
      url: jdbc:postgresql://localhost:5332/customer
      username: elaine
      password: password
    jpa:
        hibernate:
          ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false